prompt_engine/config/routes.rb
Rails.application.routes.draw do
  get "/prompt/search", to: "prompts#index"

  root "prompts#index"
end

prompt_engine/app/models/activity_log.rb
class ActivityLog < ApplicationRecord
end

prompt_engine/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

prompt_engine/app/models/concerns/searchable.rb
module Searchable
  extend ActiveSupport::Concern

  included do
    include Elasticsearch::Model
    include Elasticsearch::Model::Callbacks
  end
end

prompt_engine/app/models/prompt.rb
class Prompt < ApplicationRecord
  include Searchable
end

prompt_engine/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :info, :error, :warning
end

prompt_engine/app/controllers/prompts_controller.rb
class PromptsController < ApplicationController

  # If a search query is present, it performs an Elasticsearch search and displays the results.
  # GET /prompt/search
  def index
    # Assigning query param into another variable
    @search_query = params[:query]

    # Check if a search query is provided
    if @search_query.present?
      begin
        # Perform a search using Elasticsearch's search method with the provided query parameters
        prompts = Prompt.__elasticsearch__.search(params[:query]).response
        # Method is used to parse a JSON-formatted string
        parsed_json = JSON.parse(prompts.to_json)
        # Extract relevant data from the Elasticsearch response
        @prompts = parsed_json['hits']['hits'].map { |hit| hit['_source']['data'] }
        # Error handling for not founded prompt
        flash.now[:info] = "Please try with another keyword." unless @prompts.present?
      rescue Elasticsearch::Transport::Transport::Errors::NotFound
        # Handle error when the Elasticsearch index is not found
        flash.now[:alert] = 'Elasticsearch index not found. Please check your setup.'
      rescue Elasticsearch::Transport::Transport::Errors::RequestTimeout
        # Handle error when there's a timeout while making a request to Elasticsearch
        flash.now[:alert] = 'Elasticsearch request timed out. Please try again later.'
      rescue StandardError => e
        # Handle generic error
        flash.now[:alert] = "An error occurred: #{e.message}"
      end

      # This job is designed to perform asynchronous activity log creation
      LogCreationJob.perform_later
    end
  end
end

prompt_engine/app/helpers/application_helper.rb
module ApplicationHelper
end

prompt_engine/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AudemicPromptEngine</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'prompts', "data-turbo-track": "reload" %>
    <%#= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

prompt_engine/app/views/prompts/index.html.erb
<% flash.each do |key, message| %>
  <% if key == 'info' %>
    <div class="prompt_info">
      <span class="prompt_alert_closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
      <%= message %>.
    </div>
  <% else %>
    <div class="prompt_alert">
      <span class="prompt_alert_closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
      <%= message %>.
    </div>
  <% end %>
<% end %>

<div class="header">
  <center><h1>Search Prompts</h1></center>
</div>

<div class="row search_page_body">
  <%= form_tag(prompt_search_path, method: :get) do %>
    <div class="col-12 col-s-12 menu">
      <%= text_field_tag(:query, params[:query], placeholder: "Enter your search query", required: true) %>
      <div class="responsive-text" id="responsiveText">Search Keywords like: (The Persistence, Car)</div>
    </div>
    <div class="col-12 col-s-12 submit_div">
      <%= submit_tag('Search') %>
    </div>
  <% end %>

  <div class="col-12 col-s-12 menu">
    <% if !flash.present? && @search_query.present? %>
      <% if @prompts.present? %>
        <h3>Search Results:</h3>
        <table class="prompt_table">
          <tr></tr>
          <% @prompts.compact.each do |prompt| %>
            <tr><td><%= prompt %></td></tr>
          <% end %>
        </table>
      <% else %>
        <p>No results found.</p>
      <% end %>
    <% end %>
  </div>
</div>


<script>
  function adjustFontSize() {
    const container = document.getElementById('responsiveText');
    const containerWidth = container.clientWidth;
    const text = container.textContent;

    let fontSize = 20; // Set an initial font size

    while (container.scrollWidth > containerWidth) {
      fontSize--;
      container.style.fontSize = `${fontSize}px`;
    }
  }

  // Adjust font size on window resize
  window.addEventListener('resize', adjustFontSize);

  // Initial adjustment
  adjustFontSize();
</script>